### ISSUE TITLE
Branch for latest version of velodyne_pointcloud compatible (ros-noetic)

### ISSUE THREAD

**Issue by Chris7462** [Ford/AVData#22]
Hi all,

Since I'm using ros-noetic, I'm wondering if there is a branch compatible for latest version of velodyne_pointcloud?

As far as I know, CloudNodelet has been removed from velodyne_pointcloud in velodyne-1.6.0 as transform node includes all features of cloud node. As a result, multi_lidar_convert.launch is not working and all nodes that load velodyne_pointcloud/CloudNodelet need to be changed.

I've checked velodyne-model-fix branch, but it does not have such changes.

Thanks in advance

**Comment by ankitvora7** [comment]
Hi @Chris7462 - Apologies for the delayed response but I want to check if you were able to solve this issue ? If yes, please feel free to submit a PR

**Comment by ankitvora7** [comment]
We have also pushed a noetic-devel branch that should work with the velodyne package

**Comment by Chris7462** [comment]
Hi @ankitvora7, I tried to run `roslaunch ford_demo multi_lidar_convert.launch`, but still encounter issue as below. 

![image](https://user-images.githubusercontent.com/6722855/105445431-ed5d3080-5c3d-11eb-83f0-32e5bdd9c840.png)

**Comment by Chris7462** [comment]
Hi @ankitvora7, I think the value of "/lidar_red" should be changed to "lidar_red" in the multi_lidar_convert.launch file as below and the same for "/lidar_yellow", "/lidar_blue", and "/lidar_green".

![image](https://user-images.githubusercontent.com/6722855/105447120-96f1f100-5c41-11eb-971d-b67c0b44455c.png)

After the change, the branch works for me.

**Comment by ankitvora7** [comment]
Good catch @Chris7462 ! That's a typo there. Will correct it and push the update to the branch.

**Comment by Chris7462** [comment]
Thank you @ankitvora7 ! This issue can be closed. Really appreciate it!
